if(NOT TARGET papilo)
  include(${CMAKE_CURRENT_LIST_DIR}/papilo-targets.cmake)
endif()
set(PAPILO_IMPORTED_TARGETS papilo)
set(PAPILO_FOUND 1)

if(0)
    list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
    find_package(Quadmath)
    if(NOT Quadmath_FOUND)
        set(PAPILO_FOUND 0)
    endif()
endif()

if(NOT TBB_FOUND)
    list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})
    find_package(TBB 2018 COMPONENTS tbb tbbmalloc REQUIRED HINTS ${CMAKE_CURRENT_LIST_DIR}/_deps/local/)
endif()
if(NOT TBB_FOUND)
  set(PAPILO_FOUND 0)
endif()

find_package(Threads REQUIRED)
if(NOT Threads_FOUND)
  set(PAPILO_FOUND 0)
endif()

if(0 AND PAPILO_FOUND)
   enable_language(Fortran)
endif()
